features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://factory.png'
favicon:
  use_default: false
  path: 'public://factory.svg'
  mimetype: image/svg+xml
