preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: vertical
icon_default: true
icon_path: ''
high_contrast_mode: false
show_user_theme_settings: true
third_party_settings:
  shortcut:
    module_link: true
_core:
  default_config_hash: 7R74wb0NllX6DTTAV9sfg790XV_QXshmF0wAobLEFNQ
