<?php

/**
 * @file
 * Contains ckeditor_div.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_div_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_div module.
    case 'help.page.ckeditor_div':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module enables the Div Container Manager plugin for CKEditor.') . '</p>';
      return $output;

    default:
  }
}
