<?php
use \Drupal\Core\Access\AccessResult;
use \Drupal\node\NodeInterface;

function company_owner_theme() {
    return array(
        'owner_editing_theme' => array(
          'variables' => array(
              'data' => array(
                  'data1' => 'default'
              )
          ),
          'template' => 'newtemplate'
     )
     );
}
function company_owner_node_access(NodeInterface $node, $op) {
    $user_id = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $user_company_id = $user_id->field_propietario_empresa->getValue()[0]['target_id'];
    $company_id = $node->get('nid')->value;

    if($op === 'update') {
            echo 'CONTENT';
            return AccessResult::allowedIf( $company_id === $user_company_id );
    }
    
      return AccessResult::neutral();
}
